name: Auto approve

on:
  pull_request_target

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@7d0ab8fdbb906da8a6297d373561d5ccb137d98f # v3
      if: |
        github.actor == 'dependabot[bot]' ||
        github.actor == 'dependabot' ||
        github.actor == 'dependabot-preview[bot]' ||
        github.actor == 'dependabot-preview' ||
        github.actor == 'renovate[bot]' ||
        github.actor == 'renovate'
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
