name: Greetings

on: [pull_request_target, issues]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@2ec0f0fd78838633cd1c1342e4536d49ef72be54 # v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks for reporting this issue, don't forget to star this project if you haven't already to help us reach a wider audience."
          pr-message: "Thanks for implementing a fix, could you ensure that the test covers your changes if applicable."
